# Generated by Django 5.1.6 on 2025-02-22 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bakery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("cuisine", models.CharField(max_length=255)),
                ("rating", models.IntegerField()),
                ("image", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "bakery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bakeries.bakery",
                    ),
                ),
            ],
        ),
    ]
